artifacts_root:artifacts

data_ingestion:
  root_dir:artifacts/data_ingestion
  source_URL:"https://github.com/Puzan789/Datas/raw/main/samsumdata.zip"
  local_data_file:artifacts/data_ingestion/data.zip
  unzip-dir:artifacts/data_ingestion